version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file


services:
  mqtt2mongodb:
    logging: *default-logging
    image: umsaldanha/mqtt2mongodb
    restart: always
    volumes:
      - ${MQTT2MONGODB_PATH}/appsettings.json:/app/appsettings.json
    depends_on:
      - mongodb
      - mqtt

  mqtt:
    logging: *default-logging
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf"]

  mongodb:
    logging: *default-logging
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username_db
      MONGO_INITDB_ROOT_PASSWORD: password_db
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume: