version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  mqtt2mongodb:
    build:
      context: .
      dockerfile: ./Dockerfile
    logging: *default-logging
    image: lcas.lincoln.ac.uk/lcas/mqtt2mongodb
    restart: always
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
