version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  mqtt2mongodb:
    logging: *default-logging
    image: umsaldanha/mqtt2mongodb
    restart: always
    volumes:
      - ${MQTT2MONGODB_PATH}/appsettings.json:/app/appsettings.json
