version: '3.4'

services:
  mqtt2mongodb:
    container_name: mqtt2mongodb
    image: mqtt2mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on: 
      - mqtt
      - mongodb
    expose:
      - 5678
    ports:
      - 5678:5678
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]

  mqtt:
    image: eclipse-mosquitto
    restart: always
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883
      - 9001:9001
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto-no-auth.conf"]

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: username_db
      MONGO_INITDB_ROOT_PASSWORD: password_db
  